logging:
  level:
    ROOT: WARN
    springframework:
      web: WARN
server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: ALWAYS
springdoc:
  override-with-generic-response: false
