logging:
  level:
    ROOT: INFO
    springframework:
      web: INFO
server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: DETECT
springdoc:
  override-with-generic-response: false
